# Module 3: Data Structures Assignments
## Lesson 3.1: Lists
### Assignment 1: Creating and Accessing Lists

Create a list of the first 20 positive integers. Print the list.

### Assignment 2: Accessing List Elements

Print the first, middle, and last elements of the list created in Assignment 1.

### Assignment 3: List Slicing

Print the first five elements, the last five elements, and the elements from index 5 to 15 of the list created in Assignment 1.

### Assignment 4: List Comprehensions

Create a new list containing the squares of the first 10 positive integers using a list comprehension. Print the new list.

### Assignment 5: Filtering Lists

Create a new list containing only the even numbers from the list created in Assignment 1 using a list comprehension. Print the new list.

### Assignment 6: List Methods

Create a list of random numbers and sort it in ascending and descending order. Remove the duplicates from the list and print the modified list.

### Assignment 7: Nested Lists

Create a nested list representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

### Assignment 8: List of Dictionaries

Create a list of dictionaries where each dictionary represents a student with keys 'name' and 'score'. Sort the list of dictionaries by the 'score' in descending order and print the sorted list.

### Assignment 9: Matrix Transposition

Write a function that takes a 3x3 matrix (nested list) as input and returns its transpose. Print the original and transposed matrices.

### Assignment 10: Flattening a Nested List

Write a function that takes a nested list and flattens it into a single list. Print the original and flattened lists.

### Assignment 11: List Manipulation

Create a list of the first 10 positive integers. Remove the elements at indices 2, 4, and 6, and insert the element '99' at index 5. Print the modified list.

### Assignment 12: List Zipping

Create two lists of the same length. Use the `zip` function to combine these lists into a list of tuples and print the result.

### Assignment 13: List Reversal

Write a function that takes a list and returns a new list with the elements in reverse order. Print the original and reversed lists.

### Assignment 14: List Rotation

Write a function that rotates a list by n positions. Print the original and rotated lists.

### Assignment 15: List Intersection

Write a function that takes two lists and returns a new list containing only the elements that are present in both lists. Print the intersected list.

In [1]:
#create list and print 
numbers=[]
for num in range(1,21):
    numbers.append(num)
print(numbers)    


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [2]:
#accessing list
print(numbers[0])

1


In [3]:
#list slicing
#first 5 numbers
print(numbers[:5])
#last 5 numbers
print(numbers[15:])
#index 5 to 15
print(numbers[5:16])

[1, 2, 3, 4, 5]
[16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


In [4]:
#listcomprehension
squares=[num**2 for num in range(1,11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [5]:
#filter Even numbers
Even_numbers=[num for num in numbers if num % 2 == 0]
print(Even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [6]:
#List methods
list1=[8,45,3,75,2]
list_asc=sorted(list1)
list_desc=sorted(list1,reverse=True)
#sort asc
print(list_asc)
print(list_desc)


[2, 3, 8, 45, 75]
[75, 45, 8, 3, 2]


In [7]:
#remove duplicates
list2=[2,2,3,3,4]
result=set(list2)
print(result)

{2, 3, 4}


In [8]:
#create 3x3 matrix 
import numpy as np
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]

result=list1,list2,list3
matrix=np.array(result)
mat=np.vstack(matrix)
print(mat)
print(mat[1][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [9]:
#transpose 
transposed_mat=mat.transpose()
print('original_mat:',mat)
print('transposed_mat:',transposed_mat)

original_mat: [[1 2 3]
 [4 5 6]
 [7 8 9]]
transposed_mat: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
#flattened list
print(mat.flatten())

[1 2 3 4 5 6 7 8 9]


In [11]:
#list_manipulation
numbers=list(range(1,11))
print(numbers)
numbers.pop(2)
numbers.pop(4)
numbers.pop(6)
numbers[5]=99
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 4, 5, 7, 99, 10]


In [12]:
l1=[0,0,0,0]
l2=[1,1,1,1]
res=list(zip(l1,l2))
print(res)

[(0, 1), (0, 1), (0, 1), (0, 1)]


In [13]:
list1=[1,2,3,4]
result=list(reversed(list1))
print(result)

[4, 3, 2, 1]


In [14]:
#list of dictionaries
#list rotation
#list intersection

In [15]:
s1={'name':'q' ,'score':80}
s2 ={'name':'we','score':59}
s3={'name':'re','score':100}
students=[s1,s2,s3]
result=[]
scores=[el['score'] for el in students]
scores_new=sorted(scores,reverse=True)
for score in scores_new:
    for el in students:
        if el['score']==score:
           result.append(el)

print(result)
        

[{'name': 're', 'score': 100}, {'name': 'q', 'score': 80}, {'name': 'we', 'score': 59}]


In [17]:
#list rotation 

In [20]:
from collections import deque
ls=[1,2,3,4]
n=2 #no of positions 
d=deque(ls)
d.rotate(n)
rotated_ls=list(d)
print(rotated_ls)

[3, 4, 1, 2]


In [22]:
#list intersection #return common values
list1=[21,40,59,80]
list2=[89,90,100,80,21]
common=[]
for val in list1:
    if val in list2:
       common.append(val)
print(common)
        

[21, 80]
